export interface FacultyMember {
  id: string;
  name: string;
  designation: string;
  qualification: string;
  experience: string;
  specialization: string;
  dateOfJoining: string;
  association: string;
  bio: string;
  photo: string;
  departmentSlug: string;
}

export const allFaculty: FacultyMember[] = [
  {
    "id": "f1",
    "name": "Dr. Jane Doe",
    "designation": "Professor & Head",
    "dateOfJoining": "01/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/1.jpg",
    "departmentSlug": "artificial-intelligence-and-data-science"
  },
  {
    "id": "f2",
    "name": "Dr. John Smith",
    "designation": "Professor",
    "dateOfJoining": "15/07/2020",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "9 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/2.jpg",
    "departmentSlug": "artificial-intelligence-and-data-science"
  },
  {
    "id": "f3",
    "name": "Mr. Alex Johnson",
    "designation": "Associate Professor",
    "dateOfJoining": "10/08/2021",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "3 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/3.jpg",
    "departmentSlug": "artificial-intelligence-and-data-science"
  },
  {
    "id": "f4",
    "name": "Ms. Emily Davis",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/09/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/4.jpg",
    "departmentSlug": "artificial-intelligence-and-data-science"
  },
  {
    "id": "f5",
    "name": "Mr. Michael Brown",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/01/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "14 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/5.jpg",
    "departmentSlug": "artificial-intelligence-and-data-science"
  },
  {
    "id": "f6",
    "name": "Dr. VEDHAVATHY T R",
    "designation": "Professor & HoD",
    "dateOfJoining": "M.E., Ph.D.",
    "qualification": "Deep Learning, Data Mining, AI Systems",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/6.jpg",
    "departmentSlug": "artificial-intelligence-and-machine-learning"
  },
  {
    "id": "f7",
    "name": "Dr. JEYANTHI S",
    "designation": "Associate Professor",
    "dateOfJoining": "M.E., Ph.D.",
    "qualification": "Machine Learning, Computer Vision",
    "association": "Regular",
    "experience": "3 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/7.jpg",
    "departmentSlug": "artificial-intelligence-and-machine-learning"
  },
  {
    "id": "f8",
    "name": "Mr. RAJASEKAR R",
    "designation": "Assistant Professor",
    "dateOfJoining": "M.E., (Ph.D.)",
    "qualification": "Artificial Intelligence, Cloud AI",
    "association": "Regular",
    "experience": "2 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/8.jpg",
    "departmentSlug": "artificial-intelligence-and-machine-learning"
  },
  {
    "id": "f9",
    "name": "Mrs. AISHWARYA M S",
    "designation": "Assistant Professor",
    "dateOfJoining": "M.E.",
    "qualification": "Natural Language Processing, Web AI",
    "association": "Regular",
    "experience": "4 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/9.jpg",
    "departmentSlug": "artificial-intelligence-and-machine-learning"
  },
  {
    "id": "f10",
    "name": "Ms. SUMANA T",
    "designation": "Assistant Professor",
    "dateOfJoining": "M.Tech.",
    "qualification": "Intelligent Agents, Neural Networks",
    "association": "Regular",
    "experience": "8 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/10.jpg",
    "departmentSlug": "artificial-intelligence-and-machine-learning"
  },
  {
    "id": "f11",
    "name": "Dr. MOHAMED ADIL HAQUE",
    "designation": "Professor & Head (PG)",
    "dateOfJoining": "01/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/11.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f12",
    "name": "Dr. SOMESWARAN R",
    "designation": "Assistant Professor & Head (UG)",
    "dateOfJoining": "07/03/2022",
    "qualification": "M.Tech., Ph.D.",
    "association": "Regular",
    "experience": "2 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/12.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f13",
    "name": "Dr. ELLISS YOGESH R",
    "designation": "Professor",
    "dateOfJoining": "01/06/2021",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "10 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/13.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f14",
    "name": "Dr. VIGNESH KUMAR M",
    "designation": "Associate Professor",
    "dateOfJoining": "29/05/2023",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/14.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f15",
    "name": "Mr. RIZHA UR RAHMAN",
    "designation": "Assistant Professor",
    "dateOfJoining": "07/01/2016",
    "qualification": "M.E., (Ph.D)",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/15.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f16",
    "name": "Mr. NAVANEETHA KRISHNAN C",
    "designation": "Assistant Professor",
    "dateOfJoining": "15/03/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "16 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/16.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f17",
    "name": "Mrs. JANAKI V",
    "designation": "Assistant Professor",
    "dateOfJoining": "01/03/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/17.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f18",
    "name": "Mrs. KAVITHRA P",
    "designation": "Assistant Professor",
    "dateOfJoining": "01/08/2022",
    "qualification": "M.Tech.",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/18.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f19",
    "name": "Mr. VETRIVEL S C",
    "designation": "Assistant Professor",
    "dateOfJoining": "19/07/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/19.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f20",
    "name": "Mrs. GAYATHRI N",
    "designation": "Assistant Professor",
    "dateOfJoining": "21/07/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/20.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f21",
    "name": "Mrs. PREETHY MARY A",
    "designation": "Assistant Professor",
    "dateOfJoining": "18/07/2023",
    "qualification": "M.Tech., (Ph.D)",
    "association": "Regular",
    "experience": "2 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/21.jpg",
    "departmentSlug": "civil-engineering"
  },
  {
    "id": "f22",
    "name": "Dr. Jane Doe",
    "designation": "Professor & Head",
    "dateOfJoining": "01/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "8 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/22.jpg",
    "departmentSlug": "computer-science-and-business-systems"
  },
  {
    "id": "f23",
    "name": "Dr. John Smith",
    "designation": "Professor",
    "dateOfJoining": "15/07/2020",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "9 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/23.jpg",
    "departmentSlug": "computer-science-and-business-systems"
  },
  {
    "id": "f24",
    "name": "Mr. Alex Johnson",
    "designation": "Associate Professor",
    "dateOfJoining": "10/08/2021",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/24.jpg",
    "departmentSlug": "computer-science-and-business-systems"
  },
  {
    "id": "f25",
    "name": "Ms. Emily Davis",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/09/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/25.jpg",
    "departmentSlug": "computer-science-and-business-systems"
  },
  {
    "id": "f26",
    "name": "Mr. Michael Brown",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/01/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "4 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/26.jpg",
    "departmentSlug": "computer-science-and-business-systems"
  },
  {
    "id": "f27",
    "name": "Dr. MOHAN E",
    "designation": "Professor",
    "dateOfJoining": "26/08/2022",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "6 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/27.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f28",
    "name": "Dr. VIJAYARANGAN R",
    "designation": "Professor",
    "dateOfJoining": "19/06/2023",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "6 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/28.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f29",
    "name": "Dr. JEYANTHI S",
    "designation": "Associate Professor",
    "dateOfJoining": "13/03/2023",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/29.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f30",
    "name": "Dr. PARAMESH J",
    "designation": "Professor",
    "dateOfJoining": "06/09/2023",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "3 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/30.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f31",
    "name": "Mr. VIMALATHITHAN S",
    "designation": "Assistant Professor",
    "dateOfJoining": "09/12/2022",
    "qualification": "M.E., (Ph.D.)",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/31.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f32",
    "name": "Mr. PANDARINATHAN V",
    "designation": "Assistant Professor",
    "dateOfJoining": "18/07/2023",
    "qualification": "M.E., (Ph.D.)",
    "association": "Regular",
    "experience": "15 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/32.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f33",
    "name": "Mr. MOHIDEEN ABDUL KADHER M",
    "designation": "Assistant Professor",
    "dateOfJoining": "20/06/2018",
    "qualification": "M.E., (Ph.D)",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/33.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f34",
    "name": "Mrs. AISHWARYA M S",
    "designation": "Assistant Professor",
    "dateOfJoining": "19/12/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "9 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/34.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f35",
    "name": "Mrs. GAYATHRI S",
    "designation": "Assistant Professor",
    "dateOfJoining": "06/04/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "6 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/35.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f36",
    "name": "Mrs. MUTHU PANDEESWARI R",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/09/2022",
    "qualification": "M.E., (Ph.D.)",
    "association": "Regular",
    "experience": "8 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/36.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f37",
    "name": "Mrs. KANMANI M",
    "designation": "Assistant Professor",
    "dateOfJoining": "02/01/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "8 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/37.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f38",
    "name": "Mrs. ANGAYARKANNI N",
    "designation": "Assistant Professor",
    "dateOfJoining": "01/06/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "6 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/38.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f39",
    "name": "Mrs. GOWRI A",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/06/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "10 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/39.jpg",
    "departmentSlug": "computer-science-and-engineering"
  },
  {
    "id": "f40",
    "name": "Dr. Jane Doe",
    "designation": "Professor & Head",
    "dateOfJoining": "01/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/40.jpg",
    "departmentSlug": "cyber-security"
  },
  {
    "id": "f41",
    "name": "Dr. John Smith",
    "designation": "Professor",
    "dateOfJoining": "15/07/2020",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/41.jpg",
    "departmentSlug": "cyber-security"
  },
  {
    "id": "f42",
    "name": "Mr. Alex Johnson",
    "designation": "Associate Professor",
    "dateOfJoining": "10/08/2021",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/42.jpg",
    "departmentSlug": "cyber-security"
  },
  {
    "id": "f43",
    "name": "Ms. Emily Davis",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/09/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/43.jpg",
    "departmentSlug": "cyber-security"
  },
  {
    "id": "f44",
    "name": "Mr. Michael Brown",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/01/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "2 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/44.jpg",
    "departmentSlug": "cyber-security"
  },
  {
    "id": "f45",
    "name": "Dr. Jane Doe",
    "designation": "Professor & Head",
    "dateOfJoining": "01/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/45.jpg",
    "departmentSlug": "advanced-communication-technology"
  },
  {
    "id": "f46",
    "name": "Dr. John Smith",
    "designation": "Professor",
    "dateOfJoining": "15/07/2020",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/46.jpg",
    "departmentSlug": "advanced-communication-technology"
  },
  {
    "id": "f47",
    "name": "Mr. Alex Johnson",
    "designation": "Associate Professor",
    "dateOfJoining": "10/08/2021",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/47.jpg",
    "departmentSlug": "advanced-communication-technology"
  },
  {
    "id": "f48",
    "name": "Ms. Emily Davis",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/09/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "9 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/48.jpg",
    "departmentSlug": "advanced-communication-technology"
  },
  {
    "id": "f49",
    "name": "Mr. Michael Brown",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/01/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "6 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/49.jpg",
    "departmentSlug": "advanced-communication-technology"
  },
  {
    "id": "f50",
    "name": "Dr. K.S. Srinivasan",
    "designation": "Principal / Professor",
    "dateOfJoining": "02/05/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "16 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/50.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f51",
    "name": "Dr. I. Manju",
    "designation": "Professor & Head",
    "dateOfJoining": "15/05/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/51.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f52",
    "name": "Dr. G. Sivaranjani",
    "designation": "Assistant Professor",
    "dateOfJoining": "20/08/2020",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "15 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/52.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f53",
    "name": "Dr. S. Gopalakrishnan",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/06/2021",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "14 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/53.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f54",
    "name": "Mr. M. Syed Ali",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/07/2018",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/54.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f55",
    "name": "Mr. M. Kamarajan",
    "designation": "Assistant Professor",
    "dateOfJoining": "19/09/2019",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/55.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f56",
    "name": "Ms. S. Usha",
    "designation": "Assistant Professor",
    "dateOfJoining": "14/08/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/56.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f57",
    "name": "Ms. I. Suganthi",
    "designation": "Assistant Professor",
    "dateOfJoining": "22/11/2021",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/57.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f58",
    "name": "Ms. S. Piriyadharshini",
    "designation": "Assistant Professor",
    "dateOfJoining": "01/06/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "4 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/58.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f59",
    "name": "Ms. S. Anusuya",
    "designation": "Assistant Professor",
    "dateOfJoining": "18/03/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "10 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/59.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f60",
    "name": "Mr. M. Ashokkumar",
    "designation": "Assistant Professor",
    "dateOfJoining": "25/07/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "15 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/60.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f61",
    "name": "Ms. B. Murugeshwari",
    "designation": "Assistant Professor",
    "dateOfJoining": "10/09/2020",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "15 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/61.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f62",
    "name": "Mr. N. Rajkamal",
    "designation": "Assistant Professor",
    "dateOfJoining": "07/04/2021",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "4 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/62.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f63",
    "name": "Ms. Ajeetha Thasneem",
    "designation": "Assistant Professor",
    "dateOfJoining": "15/12/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "4 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/63.jpg",
    "departmentSlug": "electronics-and-communication-engineering"
  },
  {
    "id": "f64",
    "name": "Dr. Jane Doe",
    "designation": "Professor & Head",
    "dateOfJoining": "01/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "16 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/64.jpg",
    "departmentSlug": "vlsi-design-and-technology"
  },
  {
    "id": "f65",
    "name": "Dr. John Smith",
    "designation": "Professor",
    "dateOfJoining": "15/07/2020",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "9 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/65.jpg",
    "departmentSlug": "vlsi-design-and-technology"
  },
  {
    "id": "f66",
    "name": "Mr. Alex Johnson",
    "designation": "Associate Professor",
    "dateOfJoining": "10/08/2021",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "2 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/66.jpg",
    "departmentSlug": "vlsi-design-and-technology"
  },
  {
    "id": "f67",
    "name": "Ms. Emily Davis",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/09/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "3 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/67.jpg",
    "departmentSlug": "vlsi-design-and-technology"
  },
  {
    "id": "f68",
    "name": "Mr. Michael Brown",
    "designation": "Assistant Professor",
    "dateOfJoining": "12/01/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/68.jpg",
    "departmentSlug": "vlsi-design-and-technology"
  },
  {
    "id": "f69",
    "name": "Dr. J. Jeha",
    "designation": "Professor",
    "dateOfJoining": "10/08/2022",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "13 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/69.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f70",
    "name": "Dr. S. Devikala",
    "designation": "Professor",
    "dateOfJoining": "15/03/2023",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/70.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f71",
    "name": "Dr. A. Kamalaselvan",
    "designation": "Assistant Professor",
    "dateOfJoining": "01/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "9 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/71.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f72",
    "name": "Mr. Chintala Venkatesh",
    "designation": "Assistant Professor",
    "dateOfJoining": "14/07/2021",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "6 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/72.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f73",
    "name": "Mr. N. Suresh",
    "designation": "Assistant Professor",
    "dateOfJoining": "22/08/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/73.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f74",
    "name": "Mr. S. V. Vinodh",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/09/2020",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/74.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f75",
    "name": "Ms. K. Anupreyaa",
    "designation": "Assistant Professor",
    "dateOfJoining": "18/06/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/75.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f76",
    "name": "Ms. Achanta Gayathri",
    "designation": "Assistant Professor",
    "dateOfJoining": "25/11/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "16 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/76.jpg",
    "departmentSlug": "electrical-and-electronics-engineering"
  },
  {
    "id": "f77",
    "name": "Dr. MOHAN E",
    "designation": "Professor & HoD",
    "dateOfJoining": "M.E., Ph.D.",
    "qualification": "Distributed Systems, Cloud Computing",
    "association": "Regular",
    "experience": "3 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/77.jpg",
    "departmentSlug": "information-technology"
  },
  {
    "id": "f78",
    "name": "Mr. PANDIYAN G",
    "designation": "Assistant Professor",
    "dateOfJoining": "M.E., (Ph.D.)",
    "qualification": "Enterprise Networks, Web Technologies",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/78.jpg",
    "departmentSlug": "information-technology"
  },
  {
    "id": "f79",
    "name": "Mrs. PANDEESWARI S",
    "designation": "Assistant Professor",
    "dateOfJoining": "M.E.",
    "qualification": "Database Systems, Information Security",
    "association": "Regular",
    "experience": "13 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/79.jpg",
    "departmentSlug": "information-technology"
  },
  {
    "id": "f80",
    "name": "Mrs. GOWRI A",
    "designation": "Assistant Professor",
    "dateOfJoining": "M.E.",
    "qualification": "Full Stack Development, Software Engineering",
    "association": "Regular",
    "experience": "10 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/women/80.jpg",
    "departmentSlug": "information-technology"
  },
  {
    "id": "f81",
    "name": "Dr. SHUNMUGASUNDARAM M",
    "designation": "Professor",
    "dateOfJoining": "01/06/2015",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "8 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/81.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f82",
    "name": "Dr. JANNARTHANAN B",
    "designation": "Professor",
    "dateOfJoining": "12/08/2016",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/82.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f83",
    "name": "Dr. RAMESH G",
    "designation": "Associate Professor",
    "dateOfJoining": "15/07/2018",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/83.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f84",
    "name": "Dr. PRASATH S",
    "designation": "Associate Professor",
    "dateOfJoining": "20/06/2019",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "11 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/84.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f85",
    "name": "Dr. SARAVANAN A",
    "designation": "Associate Professor",
    "dateOfJoining": "05/09/2020",
    "qualification": "M.E., Ph.D.",
    "association": "Regular",
    "experience": "15 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/85.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f86",
    "name": "Mr. SHANMUGASELVAM P",
    "designation": "Assistant Professor",
    "dateOfJoining": "11/12/2021",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "14 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/86.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f87",
    "name": "Mr. SURESH M",
    "designation": "Assistant Professor",
    "dateOfJoining": "14/03/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "13 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/87.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f88",
    "name": "Mr. SYED ABUTHAHIR S",
    "designation": "Assistant Professor",
    "dateOfJoining": "22/07/2021",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "15 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/88.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f89",
    "name": "Mr. MOHAN S R",
    "designation": "Assistant Professor",
    "dateOfJoining": "19/08/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "10 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/89.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f90",
    "name": "Mr. MUHAMED IRFAN AA",
    "designation": "Assistant Professor",
    "dateOfJoining": "10/06/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "6 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/90.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f91",
    "name": "Mr. SAKTHIVEL D",
    "designation": "Assistant Professor",
    "dateOfJoining": "03/09/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "16 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/91.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f92",
    "name": "Mr. RAJESH J",
    "designation": "Assistant Professor",
    "dateOfJoining": "01/07/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "16 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/92.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f93",
    "name": "Mr. VIGNESHWARAN V",
    "designation": "Assistant Professor",
    "dateOfJoining": "15/05/2021",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "12 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/93.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f94",
    "name": "Mr. VINOTHKUMAR K K",
    "designation": "Assistant Professor",
    "dateOfJoining": "28/08/2022",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "7 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/94.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f95",
    "name": "Mr. THARANIKUMAR L",
    "designation": "Assistant Professor",
    "dateOfJoining": "09/02/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "5 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/95.jpg",
    "departmentSlug": "mechanical-engineering"
  },
  {
    "id": "f96",
    "name": "Mr. SUNIL KUMAR K",
    "designation": "Assistant Professor",
    "dateOfJoining": "05/11/2023",
    "qualification": "M.E.",
    "association": "Regular",
    "experience": "14 Years",
    "specialization": "Core Engineering",
    "bio": "Passionate educator and researcher dedicated to student success and academic excellence.",
    "photo": "https://randomuser.me/api/portraits/men/96.jpg",
    "departmentSlug": "mechanical-engineering"
  }
];
