/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAcademicsRouteImport } from './routes/admin.academics'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminMentorsRouteImport } from './routes/admin.mentors'
import { Route as AdminMyDepartmentRouteImport } from './routes/admin.my-department'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPlacementsRouteImport } from './routes/admin.placements'
import { Route as AdminPlacementsPortalRouteImport } from './routes/admin.placements-portal'
import { Route as AdminStartupsRouteImport } from './routes/admin.startups'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesCourseIdRouteImport } from './routes/programmes.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAcademicsRoute = AdminAcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMentorsRoute = AdminMentorsRouteImport.update({
  id: '/mentors',
  path: '/mentors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMyDepartmentRoute = AdminMyDepartmentRouteImport.update({
  id: '/my-department',
  path: '/my-department',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacementsRoute = AdminPlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlacementsPortalRoute = AdminPlacementsPortalRouteImport.update({
  id: '/placements-portal',
  path: '/placements-portal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStartupsRoute = AdminStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesCourseIdRoute = ProgrammesCourseIdRouteImport.update({
  id: '/programmes/$courseId',
  path: '/programmes/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/placements': typeof PlacementsRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/my-department': typeof AdminMyDepartmentRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/placements-portal': typeof AdminPlacementsPortalRoute
  '/admin/startups': typeof AdminStartupsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/programmes/$courseId': typeof ProgrammesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/placements': typeof PlacementsRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/my-department': typeof AdminMyDepartmentRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/placements-portal': typeof AdminPlacementsPortalRoute
  '/admin/startups': typeof AdminStartupsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/programmes/$courseId': typeof ProgrammesCourseIdRoute
  '/admin': typeof AdminIndexRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admin': typeof AdminRouteWithChildren
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/placements': typeof PlacementsRoute
  '/admin/academics': typeof AdminAcademicsRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/mentors': typeof AdminMentorsRoute
  '/admin/my-department': typeof AdminMyDepartmentRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/placements': typeof AdminPlacementsRoute
  '/admin/placements-portal': typeof AdminPlacementsPortalRoute
  '/admin/startups': typeof AdminStartupsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/programmes/$courseId': typeof ProgrammesCourseIdRoute
  '/admin/': typeof AdminIndexRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/placements'
    | '/admin/academics'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/my-department'
    | '/admin/pages'
    | '/admin/placements'
    | '/admin/placements-portal'
    | '/admin/startups'
    | '/admin/students'
    | '/events/$eventId'
    | '/programmes/$courseId'
    | '/admin/'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/placements'
    | '/admin/academics'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/my-department'
    | '/admin/pages'
    | '/admin/placements'
    | '/admin/placements-portal'
    | '/admin/startups'
    | '/admin/students'
    | '/events/$eventId'
    | '/programmes/$courseId'
    | '/admin'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admin'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/placements'
    | '/admin/academics'
    | '/admin/audit-logs'
    | '/admin/events'
    | '/admin/login'
    | '/admin/mentors'
    | '/admin/my-department'
    | '/admin/pages'
    | '/admin/placements'
    | '/admin/placements-portal'
    | '/admin/startups'
    | '/admin/students'
    | '/events/$eventId'
    | '/programmes/$courseId'
    | '/admin/'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdmissionsRoute: typeof AdmissionsRoute
  CampusLifeRoute: typeof CampusLifeRoute
  ContactRoute: typeof ContactRoute
  PlacementsRoute: typeof PlacementsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ProgrammesCourseIdRoute: typeof ProgrammesCourseIdRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/academics': {
      id: '/admin/academics'
      path: '/academics'
      fullPath: '/admin/academics'
      preLoaderRoute: typeof AdminAcademicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/mentors': {
      id: '/admin/mentors'
      path: '/mentors'
      fullPath: '/admin/mentors'
      preLoaderRoute: typeof AdminMentorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/my-department': {
      id: '/admin/my-department'
      path: '/my-department'
      fullPath: '/admin/my-department'
      preLoaderRoute: typeof AdminMyDepartmentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/placements': {
      id: '/admin/placements'
      path: '/placements'
      fullPath: '/admin/placements'
      preLoaderRoute: typeof AdminPlacementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/placements-portal': {
      id: '/admin/placements-portal'
      path: '/placements-portal'
      fullPath: '/admin/placements-portal'
      preLoaderRoute: typeof AdminPlacementsPortalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/startups': {
      id: '/admin/startups'
      path: '/startups'
      fullPath: '/admin/startups'
      preLoaderRoute: typeof AdminStartupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$courseId': {
      id: '/programmes/$courseId'
      path: '/programmes/$courseId'
      fullPath: '/programmes/$courseId'
      preLoaderRoute: typeof ProgrammesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAcademicsRoute: typeof AdminAcademicsRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminMentorsRoute: typeof AdminMentorsRoute
  AdminMyDepartmentRoute: typeof AdminMyDepartmentRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPlacementsRoute: typeof AdminPlacementsRoute
  AdminPlacementsPortalRoute: typeof AdminPlacementsPortalRoute
  AdminStartupsRoute: typeof AdminStartupsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAcademicsRoute: AdminAcademicsRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminMentorsRoute: AdminMentorsRoute,
  AdminMyDepartmentRoute: AdminMyDepartmentRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPlacementsRoute: AdminPlacementsRoute,
  AdminPlacementsPortalRoute: AdminPlacementsPortalRoute,
  AdminStartupsRoute: AdminStartupsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdminRoute: AdminRouteWithChildren,
  AdmissionsRoute: AdmissionsRoute,
  CampusLifeRoute: CampusLifeRoute,
  ContactRoute: ContactRoute,
  PlacementsRoute: PlacementsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ProgrammesCourseIdRoute: ProgrammesCourseIdRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
