/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademicsRouteImport } from './routes/academics'
import { Route as AdmissionsRouteImport } from './routes/admissions'
import { Route as CampusLifeRouteImport } from './routes/campus-life'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as PlacementsRouteImport } from './routes/placements'
import { Route as ProgrammesOfferedRouteImport } from './routes/programmes-offered'
import { Route as StudentHousingRouteImport } from './routes/student-housing'
import { Route as AboutGroupInstitutionsRouteImport } from './routes/about_.group-institutions'
import { Route as AboutLeadershipRouteImport } from './routes/about_.leadership'
import { Route as AboutOverviewRouteImport } from './routes/about_.overview'
import { Route as AboutTrustRouteImport } from './routes/about_.trust'
import { Route as AboutVisionMissionRouteImport } from './routes/about_.vision-mission'
import { Route as AdmissionsEligibilityRouteImport } from './routes/admissions_.eligibility'
import { Route as AdmissionsProcedureRouteImport } from './routes/admissions_.procedure'
import { Route as AdmissionsScholarshipsRouteImport } from './routes/admissions_.scholarships'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as ProgrammesIndexRouteImport } from './routes/programmes.index'
import { Route as ProgrammesCourseIdRouteImport } from './routes/programmes.$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicsRoute = AcademicsRouteImport.update({
  id: '/academics',
  path: '/academics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsRoute = AdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => rootRouteImport,
} as any)
const CampusLifeRoute = CampusLifeRouteImport.update({
  id: '/campus-life',
  path: '/campus-life',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacementsRoute = PlacementsRouteImport.update({
  id: '/placements',
  path: '/placements',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesOfferedRoute = ProgrammesOfferedRouteImport.update({
  id: '/programmes-offered',
  path: '/programmes-offered',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentHousingRoute = StudentHousingRouteImport.update({
  id: '/student-housing',
  path: '/student-housing',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutGroupInstitutionsRoute = AboutGroupInstitutionsRouteImport.update({
  id: '/about_/group-institutions',
  path: '/about/group-institutions',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutLeadershipRoute = AboutLeadershipRouteImport.update({
  id: '/about_/leadership',
  path: '/about/leadership',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutOverviewRoute = AboutOverviewRouteImport.update({
  id: '/about_/overview',
  path: '/about/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutTrustRoute = AboutTrustRouteImport.update({
  id: '/about_/trust',
  path: '/about/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionMissionRoute = AboutVisionMissionRouteImport.update({
  id: '/about_/vision-mission',
  path: '/about/vision-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsEligibilityRoute = AdmissionsEligibilityRouteImport.update({
  id: '/admissions_/eligibility',
  path: '/admissions/eligibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsProcedureRoute = AdmissionsProcedureRouteImport.update({
  id: '/admissions_/procedure',
  path: '/admissions/procedure',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionsScholarshipsRoute = AdmissionsScholarshipsRouteImport.update({
  id: '/admissions_/scholarships',
  path: '/admissions/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/events/$eventId',
  path: '/events/$eventId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesIndexRoute = ProgrammesIndexRouteImport.update({
  id: '/programmes/',
  path: '/programmes/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesCourseIdRoute = ProgrammesCourseIdRouteImport.update({
  id: '/programmes/$courseId',
  path: '/programmes/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/curriculum': typeof CurriculumRoute
  '/placements': typeof PlacementsRoute
  '/programmes-offered': typeof ProgrammesOfferedRoute
  '/student-housing': typeof StudentHousingRoute
  '/about/group-institutions': typeof AboutGroupInstitutionsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/overview': typeof AboutOverviewRoute
  '/about/trust': typeof AboutTrustRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/admissions/eligibility': typeof AdmissionsEligibilityRoute
  '/admissions/procedure': typeof AdmissionsProcedureRoute
  '/admissions/scholarships': typeof AdmissionsScholarshipsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/programmes/$courseId': typeof ProgrammesCourseIdRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/curriculum': typeof CurriculumRoute
  '/placements': typeof PlacementsRoute
  '/programmes-offered': typeof ProgrammesOfferedRoute
  '/student-housing': typeof StudentHousingRoute
  '/about/group-institutions': typeof AboutGroupInstitutionsRoute
  '/about/leadership': typeof AboutLeadershipRoute
  '/about/overview': typeof AboutOverviewRoute
  '/about/trust': typeof AboutTrustRoute
  '/about/vision-mission': typeof AboutVisionMissionRoute
  '/admissions/eligibility': typeof AdmissionsEligibilityRoute
  '/admissions/procedure': typeof AdmissionsProcedureRoute
  '/admissions/scholarships': typeof AdmissionsScholarshipsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/programmes/$courseId': typeof ProgrammesCourseIdRoute
  '/programmes': typeof ProgrammesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academics': typeof AcademicsRoute
  '/admissions': typeof AdmissionsRoute
  '/campus-life': typeof CampusLifeRoute
  '/contact': typeof ContactRoute
  '/credits': typeof CreditsRoute
  '/curriculum': typeof CurriculumRoute
  '/placements': typeof PlacementsRoute
  '/programmes-offered': typeof ProgrammesOfferedRoute
  '/student-housing': typeof StudentHousingRoute
  '/about_/group-institutions': typeof AboutGroupInstitutionsRoute
  '/about_/leadership': typeof AboutLeadershipRoute
  '/about_/overview': typeof AboutOverviewRoute
  '/about_/trust': typeof AboutTrustRoute
  '/about_/vision-mission': typeof AboutVisionMissionRoute
  '/admissions_/eligibility': typeof AdmissionsEligibilityRoute
  '/admissions_/procedure': typeof AdmissionsProcedureRoute
  '/admissions_/scholarships': typeof AdmissionsScholarshipsRoute
  '/events/$eventId': typeof EventsEventIdRoute
  '/programmes/$courseId': typeof ProgrammesCourseIdRoute
  '/programmes/': typeof ProgrammesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/credits'
    | '/curriculum'
    | '/placements'
    | '/programmes-offered'
    | '/student-housing'
    | '/about/group-institutions'
    | '/about/leadership'
    | '/about/overview'
    | '/about/trust'
    | '/about/vision-mission'
    | '/admissions/eligibility'
    | '/admissions/procedure'
    | '/admissions/scholarships'
    | '/events/$eventId'
    | '/programmes/$courseId'
    | '/programmes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/credits'
    | '/curriculum'
    | '/placements'
    | '/programmes-offered'
    | '/student-housing'
    | '/about/group-institutions'
    | '/about/leadership'
    | '/about/overview'
    | '/about/trust'
    | '/about/vision-mission'
    | '/admissions/eligibility'
    | '/admissions/procedure'
    | '/admissions/scholarships'
    | '/events/$eventId'
    | '/programmes/$courseId'
    | '/programmes'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academics'
    | '/admissions'
    | '/campus-life'
    | '/contact'
    | '/credits'
    | '/curriculum'
    | '/placements'
    | '/programmes-offered'
    | '/student-housing'
    | '/about_/group-institutions'
    | '/about_/leadership'
    | '/about_/overview'
    | '/about_/trust'
    | '/about_/vision-mission'
    | '/admissions_/eligibility'
    | '/admissions_/procedure'
    | '/admissions_/scholarships'
    | '/events/$eventId'
    | '/programmes/$courseId'
    | '/programmes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicsRoute: typeof AcademicsRoute
  AdmissionsRoute: typeof AdmissionsRoute
  CampusLifeRoute: typeof CampusLifeRoute
  ContactRoute: typeof ContactRoute
  CreditsRoute: typeof CreditsRoute
  CurriculumRoute: typeof CurriculumRoute
  PlacementsRoute: typeof PlacementsRoute
  ProgrammesOfferedRoute: typeof ProgrammesOfferedRoute
  StudentHousingRoute: typeof StudentHousingRoute
  AboutGroupInstitutionsRoute: typeof AboutGroupInstitutionsRoute
  AboutLeadershipRoute: typeof AboutLeadershipRoute
  AboutOverviewRoute: typeof AboutOverviewRoute
  AboutTrustRoute: typeof AboutTrustRoute
  AboutVisionMissionRoute: typeof AboutVisionMissionRoute
  AdmissionsEligibilityRoute: typeof AdmissionsEligibilityRoute
  AdmissionsProcedureRoute: typeof AdmissionsProcedureRoute
  AdmissionsScholarshipsRoute: typeof AdmissionsScholarshipsRoute
  EventsEventIdRoute: typeof EventsEventIdRoute
  ProgrammesCourseIdRoute: typeof ProgrammesCourseIdRoute
  ProgrammesIndexRoute: typeof ProgrammesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academics': {
      id: '/academics'
      path: '/academics'
      fullPath: '/academics'
      preLoaderRoute: typeof AcademicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions': {
      id: '/admissions'
      path: '/admissions'
      fullPath: '/admissions'
      preLoaderRoute: typeof AdmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campus-life': {
      id: '/campus-life'
      path: '/campus-life'
      fullPath: '/campus-life'
      preLoaderRoute: typeof CampusLifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placements': {
      id: '/placements'
      path: '/placements'
      fullPath: '/placements'
      preLoaderRoute: typeof PlacementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes-offered': {
      id: '/programmes-offered'
      path: '/programmes-offered'
      fullPath: '/programmes-offered'
      preLoaderRoute: typeof ProgrammesOfferedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-housing': {
      id: '/student-housing'
      path: '/student-housing'
      fullPath: '/student-housing'
      preLoaderRoute: typeof StudentHousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/group-institutions': {
      id: '/about_/group-institutions'
      path: '/about/group-institutions'
      fullPath: '/about/group-institutions'
      preLoaderRoute: typeof AboutGroupInstitutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/leadership': {
      id: '/about_/leadership'
      path: '/about/leadership'
      fullPath: '/about/leadership'
      preLoaderRoute: typeof AboutLeadershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/overview': {
      id: '/about_/overview'
      path: '/about/overview'
      fullPath: '/about/overview'
      preLoaderRoute: typeof AboutOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/trust': {
      id: '/about_/trust'
      path: '/about/trust'
      fullPath: '/about/trust'
      preLoaderRoute: typeof AboutTrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about_/vision-mission': {
      id: '/about_/vision-mission'
      path: '/about/vision-mission'
      fullPath: '/about/vision-mission'
      preLoaderRoute: typeof AboutVisionMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/eligibility': {
      id: '/admissions_/eligibility'
      path: '/admissions/eligibility'
      fullPath: '/admissions/eligibility'
      preLoaderRoute: typeof AdmissionsEligibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/procedure': {
      id: '/admissions_/procedure'
      path: '/admissions/procedure'
      fullPath: '/admissions/procedure'
      preLoaderRoute: typeof AdmissionsProcedureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admissions_/scholarships': {
      id: '/admissions_/scholarships'
      path: '/admissions/scholarships'
      fullPath: '/admissions/scholarships'
      preLoaderRoute: typeof AdmissionsScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/': {
      id: '/programmes/'
      path: '/programmes'
      fullPath: '/programmes/'
      preLoaderRoute: typeof ProgrammesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes/$courseId': {
      id: '/programmes/$courseId'
      path: '/programmes/$courseId'
      fullPath: '/programmes/$courseId'
      preLoaderRoute: typeof ProgrammesCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicsRoute: AcademicsRoute,
  AdmissionsRoute: AdmissionsRoute,
  CampusLifeRoute: CampusLifeRoute,
  ContactRoute: ContactRoute,
  CreditsRoute: CreditsRoute,
  CurriculumRoute: CurriculumRoute,
  PlacementsRoute: PlacementsRoute,
  ProgrammesOfferedRoute: ProgrammesOfferedRoute,
  StudentHousingRoute: StudentHousingRoute,
  AboutGroupInstitutionsRoute: AboutGroupInstitutionsRoute,
  AboutLeadershipRoute: AboutLeadershipRoute,
  AboutOverviewRoute: AboutOverviewRoute,
  AboutTrustRoute: AboutTrustRoute,
  AboutVisionMissionRoute: AboutVisionMissionRoute,
  AdmissionsEligibilityRoute: AdmissionsEligibilityRoute,
  AdmissionsProcedureRoute: AdmissionsProcedureRoute,
  AdmissionsScholarshipsRoute: AdmissionsScholarshipsRoute,
  EventsEventIdRoute: EventsEventIdRoute,
  ProgrammesCourseIdRoute: ProgrammesCourseIdRoute,
  ProgrammesIndexRoute: ProgrammesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
